App\Entities\Address:
    type: entity
    table: addresses
    id:
        id:
            type: bigint
            nullable: false
            options:
                unsigned: true
            id: true
            generator:
                strategy: IDENTITY
    fields:
        address:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        lat:
            type: float
            nullable: true
        lng:
            type: float
            nullable: true
    lifecycleCallbacks: { }
