App\Entities\Currency:
    type: entity
    table: currencies
    repositoryClass: App\Repositories\CurrencyRepository
    indexes:
        currency_remote_id_idx:
            columns:
                - code
    id:
        id:
            type: bigint
            nullable: false
            options:
                unsigned: true
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        code:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
    lifecycleCallbacks: {  }
