App\Entities\HolidayEvent:
    type: entity
    table: holiday_events
    repositoryClass: App\Repositories\HolidayEventRepository
    id:
        id:
            type: bigint
            nullable: false
            options:
                unsigned: true
            id: true
            generator:
                strategy: IDENTITY
    fields:
        title:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        date:
            type: datetime
            nullable: false
    lifecycleCallbacks: { }
