App\Entities\AnalyticsSite:
    type: entity
    table: analytics_sites
    repositoryClass: App\Repositories\AnalyticsSiteRepository

    id:
        id:
            type: bigint
            nullable: false
            options:
                unsigned: true
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        key:
            type: string
            nullable: false
            column: '`key`'
            length: 255
            options:
                fixed: false
    lifecycleCallbacks: {  }
