App\Entities\OrderStatus:
    type: entity
    table: order_statuses
    repositoryClass: App\Repositories\OrderStatusRepository
    indexes:
        order_status_remote_id_idx:
            columns:
                - remote_id
    id:
        id:
            type: bigint
            nullable: false
            options:
                unsigned: true
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        remoteId:
            type: bigint
            nullable: false
        color:
            type: string
            nullable: true
    lifecycleCallbacks: { }
