App\Entities\Tag:
    type: entity
    table: tags
    repositoryClass: App\Repositories\TagRepository
    indexes:
        tag_id_idx:
            columns:
                - id
    id:
        id:
            type: bigint
            nullable: false
            options:
                unsigned: true
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: false
            length: 255
            unique: true
            options:
                fixed: false
        color:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        keywords:
            type: json
            nullable: false
    lifecycleCallbacks: {  }
