App\Entities\MarketingChannel:
    type: entity
    table: marketing_channels
    repositoryClass: App\Repositories\MarketingChannelRepository
    id:
        id:
            type: bigint
            nullable: false
            options:
                unsigned: true
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        iconLink:
            type: string
            nullable: true
    lifecycleCallbacks: { }
