<?php

namespace DoctrineProxies\__CG__\App\Entities;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Order extends \App\Entities\Order implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entities\\Order' . "\0" . 'id', '' . "\0" . 'App\\Entities\\Order' . "\0" . 'remoteId', '' . "\0" . 'App\\Entities\\Order' . "\0" . 'packingCost', '' . "\0" . 'App\\Entities\\Order' . "\0" . 'warehouse', '' . "\0" . 'App\\Entities\\Order' . "\0" . 'createdAt', '' . "\0" . 'App\\Entities\\Order' . "\0" . 'updatedAt', '' . "\0" . 'App\\Entities\\Order' . "\0" . 'address', '' . "\0" . 'App\\Entities\\Order' . "\0" . 'currency', '' . "\0" . 'App\\Entities\\Order' . "\0" . 'customer', '' . "\0" . 'App\\Entities\\Order' . "\0" . 'market', '' . "\0" . 'App\\Entities\\Order' . "\0" . 'orderStatus'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entities\\Order' . "\0" . 'id', '' . "\0" . 'App\\Entities\\Order' . "\0" . 'remoteId', '' . "\0" . 'App\\Entities\\Order' . "\0" . 'packingCost', '' . "\0" . 'App\\Entities\\Order' . "\0" . 'warehouse', '' . "\0" . 'App\\Entities\\Order' . "\0" . 'createdAt', '' . "\0" . 'App\\Entities\\Order' . "\0" . 'updatedAt', '' . "\0" . 'App\\Entities\\Order' . "\0" . 'address', '' . "\0" . 'App\\Entities\\Order' . "\0" . 'currency', '' . "\0" . 'App\\Entities\\Order' . "\0" . 'customer', '' . "\0" . 'App\\Entities\\Order' . "\0" . 'market', '' . "\0" . 'App\\Entities\\Order' . "\0" . 'orderStatus'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Order $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getRemoteId(): string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRemoteId', []);

        return parent::getRemoteId();
    }

    /**
     * {@inheritDoc}
     */
    public function setRemoteId(string $remoteId): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRemoteId', [$remoteId]);

        parent::setRemoteId($remoteId);
    }

    /**
     * {@inheritDoc}
     */
    public function getPackingCost(): float
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPackingCost', []);

        return parent::getPackingCost();
    }

    /**
     * {@inheritDoc}
     */
    public function setPackingCost(float $packingCost): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPackingCost', [$packingCost]);

        parent::setPackingCost($packingCost);
    }

    /**
     * {@inheritDoc}
     */
    public function getWarehouse(): \App\Entities\Warehouse
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getWarehouse', []);

        return parent::getWarehouse();
    }

    /**
     * {@inheritDoc}
     */
    public function setWarehouse(\App\Entities\Warehouse $warehouse): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setWarehouse', [$warehouse]);

        parent::setWarehouse($warehouse);
    }

    /**
     * {@inheritDoc}
     */
    public function setCreatedAt(\DateTime $createdAt): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreatedAt', [$createdAt]);

        parent::setCreatedAt($createdAt);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreatedAt(): \DateTime
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreatedAt', []);

        return parent::getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setUpdatedAt(\DateTime $updatedAt): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUpdatedAt', [$updatedAt]);

        parent::setUpdatedAt($updatedAt);
    }

    /**
     * {@inheritDoc}
     */
    public function getUpdatedAt(): \DateTime
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUpdatedAt', []);

        return parent::getUpdatedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function getAddress(): \App\Entities\Address
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAddress', []);

        return parent::getAddress();
    }

    /**
     * {@inheritDoc}
     */
    public function setAddress(\App\Entities\Address $address): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAddress', [$address]);

        parent::setAddress($address);
    }

    /**
     * {@inheritDoc}
     */
    public function setCurrency(\App\Entities\Currency $currency): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCurrency', [$currency]);

        parent::setCurrency($currency);
    }

    /**
     * {@inheritDoc}
     */
    public function getCurrency(): \App\Entities\Currency
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCurrency', []);

        return parent::getCurrency();
    }

    /**
     * {@inheritDoc}
     */
    public function setCustomer(\App\Entities\Customer $customer): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCustomer', [$customer]);

        parent::setCustomer($customer);
    }

    /**
     * {@inheritDoc}
     */
    public function getCustomer(): \App\Entities\Customer
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCustomer', []);

        return parent::getCustomer();
    }

    /**
     * {@inheritDoc}
     */
    public function setMarket(\App\Entities\Market $market): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMarket', [$market]);

        parent::setMarket($market);
    }

    /**
     * {@inheritDoc}
     */
    public function getMarket(): \App\Entities\Market
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMarket', []);

        return parent::getMarket();
    }

    /**
     * {@inheritDoc}
     */
    public function setOrderStatus(\App\Entities\OrderStatus $orderStatus): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOrderStatus', [$orderStatus]);

        parent::setOrderStatus($orderStatus);
    }

    /**
     * {@inheritDoc}
     */
    public function getOrderStatus(): \App\Entities\OrderStatus
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOrderStatus', []);

        return parent::getOrderStatus();
    }

}
